### ISSUE TITLE
Adding the "EXACT_SOURCE" column to the MsigDB C5 entries 

### ISSUE THREAD

**Issue by AdrijaK** [igordot/msigdbr#10]
Thanks for the very useful package, 
would it be possible to add the EXACT_SOURCE attribute to GENESET record attributes for msigdb C5 gene sets? It would make it much easier to convert msigdb accession numbers into GO IDs. Thanks!

**Comment by igordot** [comment]
That is a good suggestion. It's not relevant for many gene sets, but it's definitely useful for the GO ones.

**Comment by steveped** [comment]
Thanks for looking into this. As an added point of interest, GO terms in MSigDB don't always match the official GO terms. For example: M22207 in MSigDB is GO_ADENOSINE_RECEPTOR_SIGNALING_PATHWAY, but when checking the EXACT_SOURCE in the MSigDB XML, the source GO term is [GO:0001973](http://amigo.geneontology.org/amigo/term/GO:0001973) which is actually 'G protein-coupled adenosine receptor signaling pathway'. Adding the Exact Source will really help relate things back to the correct ontology instead of having all of these mismatches.

And thanks again for this package which is definitely making our lives easier.

**Comment by igordot** [comment]
Thank you for bringing this to my attention and for the fix. The GitHub version of the package now includes the source field.
