### ISSUE TITLE
number of gene sets

### ISSUE THREAD

**Issue by coralzhang** [igordot/msigdbr#24]
Hi 
I am using a package version of msigdbr_7.5.1, and wonder why the number of gene sets is smaller than that listed on the website. E.g., msigdbr_collections() says that there are 1615 reactome pathways, but the website https://www.gsea-msigdb.org/gsea/msigdb/human/genesets.jsp?collection=CP:REACTOME says it is 1635? Thanks!

**Comment by igordot** [comment]
This is due to version differences. The package corresponds to MSigDB version 7.5 and the website to version 2022.1.

**Comment by ACMGlueck** [comment]
Hi Igor,
Using msigdbr version 7.5.1, when I retrieve the C8 gene set collection I obtain 700 gene sets, whereas the MSigDB website lists 830.
I suppose that this is due to the version difference issue described above. So, my question is: when / how often are the package version and the website version synchronized? When can I expect to receive all 830 gene sets?
With kind regards,
Anton

**Comment by igordot** [comment]
You are right, different versions of MSigDB will have different number of gene sets in each collection.

The package and the official database used to be fairly well-synced. The problem is that my last submission to CRAN was rejected and I have to restructure the code to comply with CRAN policies. I just haven't had time to do that.

**Comment by ACMGlueck** [comment]
Thank you for the comment, Igor. I hope that it will not give you much trouble to update your code so that it complies with the CRAN policies. Would be nice if this could be done not too far into the future, but I realize that this is just a side-activity of yours.
Best regards,
Anton
